### ISSUE TITLE
Got the error when running example with node module

### ISSUE THREAD

**Issue by lonelywolf4git** [AnyChart/AnyChart#24]
_I run the example code 
"
// require file system and jsdom
var fs = require('fs')
var jsdom = require('jsdom').jsdom

// create default jsdom view
var d = jsdom('<body><div id="container"></div></body>')
var w = d.defaultView

// require anychart and anychart export modules
var anychart = require('anychart')(w)
var anychartExport = require('anychart-nodejs')(anychart)

// create and a chart to the jsdom defaultView
var chart = anychart.pie([10, 20, 7, 18, 30])
chart.container('container')
chart.bounds(0, 0, 800, 600)
chart.draw()

// generate JPG image and save it to a file
anychartExport.exportTo(chart, 'jpg').then(function (image) {
  fs.writeFile('anychart.jpg', image, function (fsWriteError) {
    if (fsWriteError) {
      console.log(fsWriteError.message)
    } else {
      console.log('Complete')
    }
    process.exit(0)
  })
}, function (generationError) {
  console.log(generationError.message)
  process.exit(1)
})_"
and got the exception "
ypeError: this.bh.getBBox is not a function
    at ej.$.g.measure (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:704:400)
    at Oh (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:118:486)
    at $.g.gj (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:688:371)
    at ei (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:132:210)
    at $.g.iu (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:696:48)
    at $.g.Wn (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:686:34)
    at $.g.wb (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:612:125)
    at Vs (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:370:39)
    at Ms.$.g.fb (/Users/sangshh/ProjectSrcCode/json-to-chart/node_modules/anychart/dist/anychart-bundle.min.js:994:123)"

**Comment by RomanLubushkin** [comment]
@lonelywolf4git , thank you for your report, we confirm the problem and going to fix it in the upcoming release of AnyChart 8.0.2, ETA is 28th or 29th of December.

**Comment by thichpv** [comment]
this bug is fixed?
